sudo: required
language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - npm install gulp
  - npm install gulp-zip
  - npm install gulp-minify
script: gulp

# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - stable
    - develop
    - /^feature-.*$/
    - gulp_minify_artefact
