language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - npm install
  - npm install --save-dev gulp
  - npm install --save-dev gulp-zip
  - npm install --save-dev gulp-minify
script: gulp

# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - stable
    - develop
    - /^feature-.*$/
    - gulp_minify_artefact
