language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - npm install -g gulp
script: gulp

# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - stable
    - develop
    - /^feature-.*$/
