sudo: required
language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - npm install gulp
  - npm install gulp-zip
  - npm install gulp-concat
  - npm install gulp-rename
  - npm install gulp-uglify
script: gulp

# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - develop
    - /^feature-.*$/
